[package]
name = "roulette-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = "0.26.0"
anyhow = "1"
env_logger = "0.9"
indicatif = "0.17"
orao-solana-vrf = { path = "../../../../sdk" }
russian-roulette = { path = "../../programs/russian-roulette", features = ["sdk"] }
solana-cli-config = "1.10"
structopt = "0.3"
