[package]
name = "orao-solana-vrf"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

borsh = "0.9.1"
log = "0.4"
solana-client = "1.10.2"
solana-program = "1.10.2"
solana-sdk = "1.10.2"
thiserror = "1"
