[package]
name = "orao-solana-vrf"
version = "0.1.0"
edition = "2021"
homepage = "https://orao.network"
repository = "https://github.com/orao-network/solana-vrf/tree/master/rust"
license = "Apache-2.0"
keywords = ["solana", "vrf", "ed25519"]
description = "ORAO Verifiable Random Function for Solana."

[dependencies]

borsh = "0.9.1"
log = "0.4"
solana-client = "1.10.2"
solana-program = "1.10.2"
solana-sdk = "1.10.2"
thiserror = "1"
